kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: st-db2-pvc
  namespace: stocktrader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: glusterfs
